[package]
name = "circom-to-soroban-hex"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ark-bls12-381 = "0.4.0"
ark-serialize = "0.4.2"
hex = "0.4.3"
num-bigint = "0.4.6"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
